# Generated by Django 2.2.5 on 2019-09-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0002_auto_20190909_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role',
        ),
        migrations.AddField(
            model_name='role',
            name='roles',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default='student', null=True, on_delete=django.db.models.deletion.CASCADE, to='studentteacher.Role'),
        ),
    ]
