# Generated by Django 2.2.5 on 2019-09-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0003_auto_20190909_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='student', on_delete=django.db.models.deletion.CASCADE, to='studentteacher.Role'),
        ),
    ]
