# Generated by Django 2.2.5 on 2019-09-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0004_auto_20190909_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
