# Generated by Django 2.2.5 on 2019-09-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0007_auto_20190909_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='role',
        ),
    ]
