# Generated by Django 2.2.5 on 2019-09-10 08:02

from django.db import migrations, models
import studentteacher.validators


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0008_auto_20190910_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='profimg',
            field=models.ImageField(default='images/about.jpg', upload_to='images/', validators=[studentteacher.validators.validate_file_extension]),
        ),
    ]
