# Generated by Django 2.2.5 on 2019-09-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0010_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
