# Generated by Django 2.2.5 on 2019-09-11 06:12

from django.db import migrations, models
import studentteacher.validators


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0012_auto_20190911_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment',
            field=models.FileField(null=True, upload_to='documents/', validators=[studentteacher.validators.validate_file_extension1]),
        ),
    ]
