# Generated by Django 2.2.5 on 2019-09-12 12:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import studentteacher.validators


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0014_auto_20190911_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='description',
            new_name='title',
        ),
        migrations.AddField(
            model_name='assignment',
            name='requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 12, 41, 29, 953072, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_assignment', models.FileField(null=True, upload_to='documents/', validators=[studentteacher.validators.validate_file_extension1])),
                ('title', models.CharField(max_length=300)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentteacher.Assignment')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
