# Generated by Django 2.2.5 on 2019-09-12 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0016_auto_20190912_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 12, 44, 40, 8911)),
        ),
    ]
