# Generated by Django 2.2.5 on 2019-09-12 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0020_auto_20190912_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 13, 2, 50, 761677)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 13, 2, 50, 762305)),
        ),
    ]
