# Generated by Django 2.2.5 on 2019-09-12 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0021_auto_20190912_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 13, 3, 35, 395226)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 13, 3, 35, 395253)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 13, 3, 35, 395857)),
        ),
    ]
