# Generated by Django 2.2.5 on 2019-09-12 13:08

import datetime
from django.db import migrations, models
import studentteacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0022_auto_20190912_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(blank=True, default=studentteacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 13, 8, 11, 220204)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 13, 8, 11, 220820)),
        ),
    ]
