# Generated by Django 2.2.5 on 2019-09-12 13:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0023_auto_20190912_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='student',
            new_name='sub_student',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='teacher',
            new_name='sub_teacher',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='requested',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 13, 42, 40, 343666)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 13, 42, 40, 344295)),
        ),
        migrations.CreateModel(
            name='AssignRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.BooleanField(default=False)),
                ('req_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_student', to=settings.AUTH_USER_MODEL)),
                ('req_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
