# Generated by Django 2.2.5 on 2019-09-13 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0025_auto_20190912_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 5, 14, 5, 604710)),
        ),
        migrations.AlterField(
            model_name='assignrequest',
            name='requested',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 5, 14, 5, 605329)),
        ),
    ]
