# Generated by Django 2.2.5 on 2019-09-13 07:16

import datetime
from django.db import migrations, models
import studentteacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0026_auto_20190913_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateField(blank=True, default=studentteacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
