# Generated by Django 2.2.5 on 2019-09-13 07:26

import datetime
from django.db import migrations, models
import studentteacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0027_auto_20190913_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(blank=True, default=studentteacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 7, 26, 34, 904821)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 7, 26, 34, 905473)),
        ),
    ]
