# Generated by Django 2.2.5 on 2019-09-13 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0030_auto_20190913_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='title',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='assignment',
            new_name='tea_assignment',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 8, 2, 14, 588608)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 8, 2, 14, 589306)),
        ),
    ]
