# Generated by Django 2.2.5 on 2019-09-13 09:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0032_auto_20190913_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 9, 54, 3, 779847)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 9, 54, 3, 780468)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_stars', models.CharField(max_length=20)),
                ('review_assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentteacher.Submission')),
                ('review_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_student', to=settings.AUTH_USER_MODEL)),
                ('review_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
