# Generated by Django 2.2.5 on 2019-09-13 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0033_auto_20190913_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 10, 14, 53, 330383)),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_stars',
            field=models.CharField(choices=[('1 star', '1 star'), ('1.5 star', '1.5 star'), ('2 star', '2 star'), ('2.5 star', '2.5 star'), ('3 star', '3 star'), ('3.5 star', '3.5 star'), ('4 star', '4 star'), ('4.5 star', '4.5 star'), ('5 star', '5 star')], default='3 star', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 10, 14, 53, 331009)),
        ),
    ]
