# Generated by Django 2.2.5 on 2019-09-17 06:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0037_auto_20190916_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='type',
        ),
        migrations.AddField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 17, 6, 39, 59, 949335)),
        ),
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 17, 6, 39, 59, 947529)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 17, 6, 39, 59, 948135)),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
