# Generated by Django 2.2.5 on 2019-09-17 07:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0039_auto_20190917_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 17, 7, 12, 43, 868882)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 17, 7, 12, 43, 870726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 17, 7, 12, 43, 869511)),
        ),
    ]
