# Generated by Django 2.2.5 on 2019-09-17 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentteacher', '0043_auto_20190917_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 17, 9, 43, 24, 330455)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 17, 9, 43, 24, 331100)),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
